# Call as:
#   Rscript build.R  
#   Rscript build.R --full  # rebuild all img from pdf
args = "" #c( "--full" )
if (!interactive())
    args = commandArgs(TRUE)
smart = !stom::cmd_has(args, "--full")

for ( fp in Sys.glob("*/PDF/*.pdf") ) {
    # Skip if img already exists
    if ( smart ) {
        img = file.path( dirname(fp), 
                         paste0(basename(xfun::sans_ext(fp)),"*.png") )
        if ( length(Sys.glob(img)) > 0 ) next
    }
    stom::pdf2png(fp, dpi=300, white = TRUE)
}

get_dir_links = function(dir_) {
    sapply(Sys.glob( file.path(dir_,"PDF/*.pdf") ), function (pdf) {
        baseurl = "https://github.com/liao961120/snippets/tree/main"
        dir_pdf = dirname(pdf)
        dir_src = dirname(dir_pdf)
        fstem = basename(pdf) |> tools::file_path_sans_ext()
        
        src = file.path( dir_src, paste0(fstem,".tex") )
        imgs = Sys.glob( paste0(dir_pdf,"/",fstem,"*.png") )
        
        src_text = glue::glue("#### [`{basename(src)}`]({baseurl}/{src})")
        # img_text = glue::glue("   ![]({imgs})  ")
        img_text = paste0('   <img src="', imgs, '" style="display:block;max-height:300px;max-width:370px; margin:0 auto; padding: 0 auto;" />')
        md = paste( c(src_text,img_text), collapse="\n" )
        return(md)
    }) |> paste(collapse="\n\n")
}
# LINKS |> cat()
LINKS_eq = get_dir_links("eq")
LINKS_tikz = get_dir_links("tikz")


GALLERY = glue::glue("
<!-- The content below is autogenerated, edit build.R instead. -->

Gallery
-------

### Graphs

{LINKS_tikz}

### Equations

{LINKS_eq}
")


# Compile documents
Sys.setlocale("LC_ALL","English")
pd_args = c(#"--number-sections", 
            "-V", 
            paste0("date=",'"',format.Date(Sys.Date(),"%B %d, %Y"),'"'),
            "--shift-heading-level-by=-1"
)

# Plug GALLERY at the end of `eq.md` to generate `README.md` and `index.html`
README = c( xfun::read_utf8("eq.md"), GALLERY )
xfun::write_utf8(README, "README.md")
stom::pandoc_html("README.md", "index.html", pd_args)
