# Call as:
#   Rscript build.R  
#   Rscript build.R --full  # rebuild all img from pdf
args = "" #c( "--full" )
if (!interactive())
    args = commandArgs(TRUE)
smart = !stom::cmd_has(args, "--full")

for ( fp in Sys.glob("*/PDF/*.pdf") ) {
    # Skip if img already exists
    if ( smart ) {
        img = file.path( dirname(fp), 
                         paste0(basename(xfun::sans_ext(fp)),"*.png") )
        if ( length(Sys.glob(img)) > 0 ) next
    }
    stom::pdf2png(fp, dpi=300, white = TRUE)
}

LINKS = sapply(Sys.glob("*/PDF/*.pdf"), function (pdf) {
    dir_pdf = dirname(pdf)
    dir_src = dirname(dir_pdf)
    fstem = basename(pdf) |> tools::file_path_sans_ext()
    
    src = file.path( dir_src, paste0(fstem,".tex") )
    imgs = Sys.glob( paste0(dir_pdf,"/",fstem,"*.png") )
    
    src_text = glue::glue("1. [`{basename(src)}`]({src})  ")
    # img_text = glue::glue("   ![]({imgs})  ")
    img_text = paste0('   <img src="', imgs, '" width=380px />  ')
    md = paste( c(src_text,img_text), collapse="\n" )
    return(md)
}) |> paste(collapse="\n")
# LINKS |> cat()


README = glue::glue("
<!-- This file is autogenerated, edit build.R instead. -->

Personal LaTeX Snippets
=======================

This directory holds the snippets of equations and TikZ graphs I've coded.

To search the content inside the `.tex` files, run:

```bash
bash search.sh SEARCH_TERM
```

To update the gallery below, run:

```bash
Rscript build.R
# Rscript build.R --full  # rebuild all img from pdf
```

Gallery
-------

{LINKS}
")

xfun::write_utf8(README, "README.md")
stom::pandoc_html("README.md", "README.html")
